kind: ConfigMap
apiVersion: v1
metadata:
  name: oamd-config
data:
  config.yml: |-
    server:
      addr: ":8080"
    oam:
      serviceID: cloud1234
      controllerAddr: "oam-controller-svc:7777"
      controllerSslCaFile: "/etc/oamd/ssl/icomcloud-pki/icomcloud-ca.crt"
      # controllerServerHostOverride: "oam-controller-nsys.eu-west-1.icomcloud.net"
      controllerServerHostOverride: ""
